include: package:lints/core.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Add common rules for the workspace
    - always_declare_return_types
    - avoid_print
    - prefer_final_locals
    - unnecessary_this
