// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
// Source: test/fixtures/gen_vocab_minimal_test_models.dart

// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field, unnecessary_string_interpolations

import 'package:locorda_rdf_core/core.dart';
import 'package:locorda_rdf_mapper/mapper.dart';

// Other imports
import 'gen_vocab_minimal_test_models.dart';

/// Generated mapper for [GenVocabMinimalEntity] global resources.
///
/// This mapper handles serialization and deserialization between Dart objects
/// and RDF triples for resources of type `GenVocabMinimalEntity`.
class GenVocabMinimalEntityMapper
    implements GlobalResourceMapper<GenVocabMinimalEntity> {
  static final RegExp _regex = RegExp(
    r'^https://example\.com/minimal/(?<id>[^/]*)$',
  );

  /// Constructor
  const GenVocabMinimalEntityMapper();

  @override
  IriTerm? get typeIri =>
      const IriTerm('https://minimal.example.com/vocab#GenVocabMinimalEntity');

  @override
  GenVocabMinimalEntity fromRdfResource(
    IriTerm subject,
    DeserializationContext context,
  ) {
    final reader = context.reader(subject);

    final RegExpMatch? match = _regex.firstMatch(subject.value);

    final iriParts = {
      for (var name in (match?.groupNames ?? const <String>[]))
        name: match?.namedGroup(name) ?? '',
    };

    final id = iriParts['id'];
    if (id == null) {
      throw DeserializationException(
        'Missing required IRI part: id in IRI ${subject.value}',
      );
    }
    final String minimalName = reader.require(
      const IriTerm('https://minimal.example.com/vocab#minimalName'),
    );
    final DateTime? lastModified = reader.optional(
      const IriTerm('https://minimal.example.com/vocab#lastModified'),
    );

    return GenVocabMinimalEntity(
      id: id,
      minimalName: minimalName,
      lastModified: lastModified,
    );
  }

  @override
  (IriTerm, Iterable<Triple>) toRdfResource(
    GenVocabMinimalEntity resource,
    SerializationContext context, {
    RdfSubject? parentSubject,
  }) {
    final subject = context.createIriTerm(_buildIri(resource));

    return context
        .resourceBuilder(subject)
        .addValue(
          const IriTerm('https://minimal.example.com/vocab#minimalName'),
          resource.minimalName,
        )
        .build();
  }

  /// Builds the IRI for a resource instance using the IRI template.
  String _buildIri(GenVocabMinimalEntity resource) {
    final id = resource.id;
    return 'https://example.com/minimal/${id}';
  }
}
