// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
//
// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field

import 'package:locorda_rdf_mapper/mapper.dart';

import 'fixtures/annotation_subclass_test_models.dart' as astm;
import 'fixtures/annotation_subclass_test_models.rdf_mapper.g.dart' as astmrmg;
import 'fixtures/annotation_test_models.dart' as atm;
import 'fixtures/annotation_test_models.rdf_mapper.g.dart' as atmrmg;
import 'fixtures/comprehensive_collection_tests.dart' as cct;
import 'fixtures/comprehensive_collection_tests.rdf_mapper.g.dart' as cctrmg;
import 'fixtures/directional_comprehensive_test_models.dart' as dctm;
import 'fixtures/directional_comprehensive_test_models.rdf_mapper.g.dart'
    as dctmrmg;
import 'fixtures/directional_mapper_test_models.dart' as dmtm;
import 'fixtures/directional_mapper_test_models.rdf_mapper.g.dart' as dmtmrmg;
import 'fixtures/enum_test_models.dart' as etm;
import 'fixtures/enum_test_models.rdf_mapper.g.dart' as etmrmg;
import 'fixtures/gen_vocab_minimal_test_models.dart' as gvmtm;
import 'fixtures/gen_vocab_minimal_test_models.rdf_mapper.g.dart' as gvmtmrmg;
import 'fixtures/gen_vocab_processor_test_models.dart' as gvptm;
import 'fixtures/gen_vocab_processor_test_models.rdf_mapper.g.dart' as gvptmrmg;
import 'fixtures/global_resource_processor_test_models.dart' as grptm;
import 'fixtures/global_resource_processor_test_models.rdf_mapper.g.dart'
    as grptmrmg;
import 'fixtures/iri_processor_test_models.dart' as iptm;
import 'fixtures/iri_processor_test_models.rdf_mapper.g.dart' as iptmrmg;
import 'fixtures/literal_processor_test_models.dart' as lptm;
import 'fixtures/literal_processor_test_models.rdf_mapper.g.dart' as lptmrmg;
import 'fixtures/local_resource_processor_test_models.dart' as lrptm;
import 'fixtures/local_resource_processor_test_models.rdf_mapper.g.dart'
    as lrptmrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/collection_examples.dart'
    as ce;
import 'fixtures/locorda_rdf_mapper_annotations/examples/collection_examples.rdf_mapper.g.dart'
    as cermg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/custom_collection_type_example.dart'
    as ccte;
import 'fixtures/locorda_rdf_mapper_annotations/examples/custom_collection_type_example.rdf_mapper.g.dart'
    as cctermg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/enum_mapping_simple.dart'
    as ems;
import 'fixtures/locorda_rdf_mapper_annotations/examples/enum_mapping_simple.rdf_mapper.g.dart'
    as emsrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_crdt_item.dart'
    as eci;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_crdt_item.rdf_mapper.g.dart'
    as ecirmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_full_book.dart'
    as efb;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_full_book.rdf_mapper.g.dart'
    as efbrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_iri_strategies.dart'
    as eis;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_iri_strategies.rdf_mapper.g.dart'
    as eisrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_rdf_literal.dart'
    as erl;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_rdf_literal.rdf_mapper.g.dart'
    as erlrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/inference.dart'
    as inference;
import 'fixtures/locorda_rdf_mapper_annotations/examples/inference.rdf_mapper.g.dart'
    as irmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/localized_string_map.dart'
    as lsm;
import 'fixtures/locorda_rdf_mapper_annotations/examples/localized_string_map.rdf_mapper.g.dart'
    as lsmrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/provides.dart'
    as provides;
import 'fixtures/locorda_rdf_mapper_annotations/examples/provides.rdf_mapper.g.dart'
    as prmg;
import 'fixtures/named_factory_test_models.dart' as nftm;
import 'fixtures/named_factory_test_models.rdf_mapper.g.dart' as nftmrmg;
import 'fixtures/property_processor_test_models.dart' as pptm;
import 'fixtures/property_processor_test_models.rdf_mapper.g.dart' as pptmrmg;
import 'fixtures/provided_as_test_models.dart' as patm;
import 'fixtures/provided_as_test_models.rdf_mapper.g.dart' as patmrmg;
import 'fixtures/root_document.dart' as rd;
import 'fixtures/root_document.rdf_mapper.g.dart' as rdrmg;
import 'fixtures/unmapped_triples_test_models.dart' as uttm;
import 'fixtures/unmapped_triples_test_models.rdf_mapper.g.dart' as uttmrmg;
import 'fixtures/valid_generic_test_models.dart' as vgtm;
import 'fixtures/valid_generic_test_models.rdf_mapper.g.dart' as vgtmrmg;
import 'fixtures/with_fragment_test_models.dart' as wftm;
import 'fixtures/with_fragment_test_models.rdf_mapper.g.dart' as wftmrmg;

/// Initializes and returns an RdfMapper with test mappers registered.
///
/// [rdfMapper] An optional RdfMapper instance to use. If not provided, a new one will be created.
/// * [$podIri$Factory]
/// * [apiBaseProvider]
/// * [baseUriProvider]
/// * [baseVocabProvider]
/// * [chapterIdMapper]
/// * [complexItemMapperGlobal]
/// * [complexItemMapperLocal]
/// * [configurableBookIriFactory]
/// * [customCollectionMapper]
/// * [customPriorityMapper]
/// * [departmentProvider]
/// * [iriMapper]
/// * [mapEntryMapper]
/// * [orgNamespaceProvider]
/// * [simpleBookIriFactory]
/// * [simpleVariantRefFactory]
/// * [storageRootProvider]
/// * [testCustomMapper]
/// * [testGlobalMapper]
/// * [testGlobalResourceMapper]
/// * [testIriMapper]
/// * [testLiteralMapper]
/// * [testLiteralPriceMapper]
/// * [testLocalMapper]
/// * [testLocalResourceMapper]
/// * [testMapper]
/// * [testMapper3]
/// * [testNamedMapper]
/// * [userReferenceMapper]
/// * [versionProvider]
RdfMapper initTestRdfMapper({
  RdfMapper? rdfMapper,
  required IriTermMapper<(String id,)> Function<T>(astm.PodConfig)
  $podIri$Factory,
  required String Function() apiBaseProvider,
  required String Function() baseUriProvider,
  required String Function() baseVocabProvider,
  required IriTermMapper<(String bookId, int chapterNumber)> chapterIdMapper,
  required GlobalResourceMapper<cct.ComplexItem> complexItemMapperGlobal,
  required LocalResourceMapper<cct.ComplexItem> complexItemMapperLocal,
  required IriTermMapper<(String id,)> Function<T>(nftm.IriMapperConfig)
  configurableBookIriFactory,
  required Mapper<List<String>> customCollectionMapper,
  required LiteralTermMapper<ems.Priority> customPriorityMapper,
  required String Function() departmentProvider,
  required IriTermMapper<String> iriMapper,
  required LocalResourceMapper<MapEntry<String, String>> mapEntryMapper,
  required String Function() orgNamespaceProvider,
  required IriTermMapper<(String id,)> Function<T>() simpleBookIriFactory,
  required IriTermMapper<String> Function<T>(Type) simpleVariantRefFactory,
  required String Function() storageRootProvider,
  required LiteralTermMapper<String> testCustomMapper,
  required GlobalResourceMapper<Object> testGlobalMapper,
  required GlobalResourceMapper<grptm.ClassWithMapperNamedMapperStrategy>
  testGlobalResourceMapper,
  required IriTermMapper<iptm.IriWithNamedMapper> testIriMapper,
  required LiteralTermMapper<lptm.LiteralWithNamedMapper> testLiteralMapper,
  required LiteralTermMapper<double> testLiteralPriceMapper,
  required LocalResourceMapper<Object> testLocalMapper,
  required LocalResourceMapper<lrptm.ClassWithMapperNamedMapperStrategy>
  testLocalResourceMapper,
  required IriTermMapper<grptm.ClassWithIriNamedMapperStrategy> testMapper,
  required IriTermMapper<(String id, String surname, int version)> testMapper3,
  required GlobalResourceMapper<Object> testNamedMapper,
  required IriTermMapper<eis.UserReference> userReferenceMapper,
  required String Function() versionProvider,
}) {
  if (rdfMapper == null) {
    rdfMapper = RdfMapper.withDefaultRegistry();
  }
  var registry = rdfMapper.registry;

  registry.registerMapper<astm.BookWithCustomAnnotation>(
    astmrmg.BookWithCustomAnnotationMapper(),
  );
  registry.registerMapper<astm.PersonWithPodResource>(
    astmrmg.PersonWithPodResourceMapper(),
  );
  registry.registerMapper<astm.PersonWithPodResource2>(
    astmrmg.PersonWithPodResource2Mapper(
      iriMapper: $podIri$Factory<astm.PersonWithPodResource2>(
        const astm.PodConfig(digits: 2),
      ),
    ),
  );
  registry.registerMapper<astm.ArticleWithRegularAnnotation>(
    astmrmg.ArticleWithRegularAnnotationMapper(),
  );
  registry.registerMapper<atm.BookWithMapper>(atmrmg.BookWithMapperMapper());
  registry.registerMapper<atm.BookWithTemplate>(
    atmrmg.BookWithTemplateMapper(),
  );
  registry.registerMapper<cct.RegistryCollectionTests>(
    cctrmg.RegistryCollectionTestsMapper(),
  );
  registry.registerMapper<cct.NamedMapperCollectionTests>(
    cctrmg.NamedMapperCollectionTestsMapper(
      customCollectionMapper: customCollectionMapper,
    ),
  );
  registry.registerMapper<cct.SelfContainedMapperTests>(
    cctrmg.SelfContainedMapperTestsMapper(),
  );
  registry.registerMapper<cct.InstanceManagedCollectionTests>(
    cctrmg.InstanceManagedCollectionTestsMapper(),
  );
  registry.registerMapper<cct.SetAndIterableCollectionTests>(
    cctrmg.SetAndIterableCollectionTestsMapper(),
  );
  registry.registerMapper<cct.ComplexItem>(cctrmg.ComplexItemMapper());
  registry.registerMapper<cct.ItemTypeParameterTests>(
    cctrmg.ItemTypeParameterTestsMapper(
      complexItemMapperLocal: complexItemMapperLocal,
    ),
  );
  registry.registerMapper<cct.CombinedItemMappingTests>(
    cctrmg.CombinedItemMappingTestsMapper(
      baseUriProvider: baseUriProvider,
      complexItemMapperGlobal: complexItemMapperGlobal,
    ),
  );
  registry.registerMapper<cct.EdgeCaseTests>(cctrmg.EdgeCaseTestsMapper());
  registry.registerMapper<cct.PerformanceTests>(
    cctrmg.PerformanceTestsMapper(),
  );
  registry.registerMapper<cct.MapCollectionTests>(
    cctrmg.MapCollectionTestsMapper(),
  );
  registry.registerMapper<cct.DefaultSerializationTests>(
    cctrmg.DefaultSerializationTestsMapper(),
  );
  registry.registerMapper<cct.NestedCollectionTests>(
    cctrmg.NestedCollectionTestsMapper(),
  );
  registry.registerMapper<cct.MixedTypeTests>(cctrmg.MixedTypeTestsMapper());
  registry.registerMapper<cct.ContextProviderTests>(
    cctrmg.ContextProviderTestsMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyGlobalResource>(
    dctmrmg.DeserializeOnlyGlobalResourceMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyGlobalResource>(
    dctmrmg.SerializeOnlyGlobalResourceMapper(),
  );
  registry.registerMapper<dctm.BidirectionalGlobalResource>(
    dctmrmg.BidirectionalGlobalResourceMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyLocalResource>(
    dctmrmg.DeserializeOnlyLocalResourceMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyLocalResource>(
    dctmrmg.SerializeOnlyLocalResourceMapper(),
  );
  registry.registerMapper<dctm.BidirectionalLocalResource>(
    dctmrmg.BidirectionalLocalResourceMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyIriClass>(
    dctmrmg.DeserializeOnlyIriClassMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyIriClass>(
    dctmrmg.SerializeOnlyIriClassMapper(),
  );
  registry.registerMapper<dctm.BidirectionalIriClass>(
    dctmrmg.BidirectionalIriClassMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyLiteralClass>(
    dctmrmg.DeserializeOnlyLiteralClassMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyLiteralClass>(
    dctmrmg.SerializeOnlyLiteralClassMapper(),
  );
  registry.registerMapper<dctm.BidirectionalLiteralClass>(
    dctmrmg.BidirectionalLiteralClassMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyIriEnum>(
    dctmrmg.DeserializeOnlyIriEnumMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyIriEnum>(
    dctmrmg.SerializeOnlyIriEnumMapper(),
  );
  registry.registerMapper<dctm.BidirectionalIriEnum>(
    dctmrmg.BidirectionalIriEnumMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyLiteralEnum>(
    dctmrmg.DeserializeOnlyLiteralEnumMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyLiteralEnum>(
    dctmrmg.SerializeOnlyLiteralEnumMapper(),
  );
  registry.registerMapper<dctm.BidirectionalLiteralEnum>(
    dctmrmg.BidirectionalLiteralEnumMapper(),
  );
  registry.registerDeserializer<dmtm.DeserializeOnlyClass>(
    dmtmrmg.DeserializeOnlyClassMapper(),
  );
  registry.registerSerializer<dmtm.SerializeOnlyClass>(
    dmtmrmg.SerializeOnlyClassMapper(),
  );
  registry.registerMapper<dmtm.BidirectionalClass>(
    dmtmrmg.BidirectionalClassMapper(),
  );
  registry.registerMapper<etm.Priority>(etmrmg.PriorityMapper());
  registry.registerMapper<etm.Status>(etmrmg.StatusMapper());
  registry.registerMapper<etm.DocumentType>(etmrmg.DocumentTypeMapper());
  registry.registerMapper<etm.CategoryType>(etmrmg.CategoryTypeMapper());
  registry.registerMapper<etm.FileFormat>(
    etmrmg.FileFormatMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<gvmtm.GenVocabMinimalEntity>(
    gvmtmrmg.GenVocabMinimalEntityMapper(),
  );
  registry.registerMapper<gvptm.GenVocabBook>(gvptmrmg.GenVocabBookMapper());
  registry.registerMapper<gvptm.GenVocabLibraryItem>(
    gvptmrmg.GenVocabLibraryItemMapper(),
  );
  registry.registerMapper<gvptm.GenVocabContract>(
    gvptmrmg.GenVocabContractMapper(),
  );
  registry.registerMapper<gvptm.GenVocabMultilingualProduct>(
    gvptmrmg.GenVocabMultilingualProductMapper(),
  );
  registry.registerMapper<gvptm.GenVocabArticle>(
    gvptmrmg.GenVocabArticleMapper(),
  );
  registry.registerMapper<gvptm.GenVocabPropertyTypeOverride>(
    gvptmrmg.GenVocabPropertyTypeOverrideMapper(),
  );
  registry.registerMapper<grptm.Book>(grptmrmg.BookMapper());
  registry.registerMapper<grptm.ClassWithEmptyIriStrategy>(
    grptmrmg.ClassWithEmptyIriStrategyMapper(),
  );
  registry.registerMapper<grptm.ClassWithNoRdfType>(
    grptmrmg.ClassWithNoRdfTypeMapper(),
  );
  registry.registerMapper<grptm.ClassWithIriTemplateStrategy>(
    grptmrmg.ClassWithIriTemplateStrategyMapper(),
  );
  registry.registerMapper<grptm.ClassWithIriTemplateAndContextVariableStrategy>(
    grptmrmg.ClassWithIriTemplateAndContextVariableStrategyMapper(
      baseUriProvider: baseUriProvider,
    ),
  );
  registry.registerMapper<grptm.ClassWithIriNamedMapperStrategy>(
    grptmrmg.ClassWithIriNamedMapperStrategyMapper(testMapper: testMapper),
  );
  registry.registerMapper<
    grptm.ClassWithIriNamedMapperStrategy2PartsWithProperties
  >(
    grptmrmg.ClassWithIriNamedMapperStrategy2PartsWithPropertiesMapper(
      testMapper3: testMapper3,
    ),
  );
  registry.registerMapper<grptm.ClassWithIriMapperStrategy>(
    grptmrmg.ClassWithIriMapperStrategyMapper(),
  );
  registry.registerMapper<grptm.ClassWithIriMapperInstanceStrategy>(
    grptmrmg.ClassWithIriMapperInstanceStrategyMapper(),
  );
  registry.registerMapper<grptm.ClassWithMapperNamedMapperStrategy>(
    testGlobalResourceMapper,
  );
  registry.registerMapper<grptm.ClassWithMapperStrategy>(
    grptm.TestGlobalResourceMapper(),
  );
  registry.registerMapper<grptm.ClassWithMapperInstanceStrategy>(
    const grptm.TestGlobalResourceMapper2(),
  );
  registry.registerMapper<iptm.IriWithOnePart>(iptmrmg.IriWithOnePartMapper());
  registry.registerMapper<iptm.IriWithOnePartExplicitlyGlobal>(
    iptmrmg.IriWithOnePartExplicitlyGlobalMapper(),
  );
  registry.registerMapper<iptm.IriWithOnePartNamed>(
    iptmrmg.IriWithOnePartNamedMapper(),
  );
  registry.registerMapper<iptm.IriWithTwoParts>(
    iptmrmg.IriWithTwoPartsMapper(),
  );
  registry.registerMapper<iptm.IriWithBaseUriAndTwoParts>(
    iptmrmg.IriWithBaseUriAndTwoPartsMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<iptm.IriWithBaseUri>(
    iptmrmg.IriWithBaseUriMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<iptm.IriWithNamedMapper>(testIriMapper);
  registry.registerMapper<iptm.IriWithMapper>(iptm.TestIriMapper());
  registry.registerMapper<iptm.IriWithMapperInstance>(
    const iptm.TestIriMapper2(),
  );
  registry.registerMapper<iptm.IriWithNonConstructorFields>(
    iptmrmg.IriWithNonConstructorFieldsMapper(),
  );
  registry.registerMapper<iptm.IriWithMixedFields>(
    iptmrmg.IriWithMixedFieldsMapper(),
  );
  registry.registerMapper<lptm.LiteralString>(lptmrmg.LiteralStringMapper());
  registry.registerMapper<lptm.Rating>(lptmrmg.RatingMapper());
  registry.registerMapper<lptm.LocalizedText>(lptmrmg.LocalizedTextMapper());
  registry.registerMapper<lptm.LiteralDouble>(lptmrmg.LiteralDoubleMapper());
  registry.registerMapper<lptm.LiteralInteger>(lptmrmg.LiteralIntegerMapper());
  registry.registerMapper<lptm.Temperature>(lptmrmg.TemperatureMapper());
  registry.registerMapper<lptm.CustomLocalizedText>(
    lptmrmg.CustomLocalizedTextMapper(),
  );
  registry.registerMapper<lptm.DoubleAsMilliunit>(
    lptmrmg.DoubleAsMilliunitMapper(),
  );
  registry.registerMapper<lptm.LiteralWithNamedMapper>(testLiteralMapper);
  registry.registerMapper<lptm.LiteralWithMapper>(lptm.TestLiteralMapper());
  registry.registerMapper<lptm.LiteralWithMapperInstance>(
    const lptm.TestLiteralMapper2(),
  );
  registry.registerMapper<lptm.LiteralWithNonConstructorValue>(
    lptmrmg.LiteralWithNonConstructorValueMapper(),
  );
  registry.registerMapper<lptm.LocalizedTextWithNonConstructorLanguage>(
    lptmrmg.LocalizedTextWithNonConstructorLanguageMapper(),
  );
  registry.registerMapper<lptm.LiteralLateFinalLocalizedText>(
    lptmrmg.LiteralLateFinalLocalizedTextMapper(),
  );
  registry.registerMapper<lrptm.Book>(lrptmrmg.BookMapper());
  registry.registerMapper<lrptm.ClassWithNoRdfType>(
    lrptmrmg.ClassWithNoRdfTypeMapper(),
  );
  registry.registerMapper<lrptm.ClassWithPositionalProperty>(
    lrptmrmg.ClassWithPositionalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithNonFinalProperty>(
    lrptmrmg.ClassWithNonFinalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithNonFinalPropertyWithDefault>(
    lrptmrmg.ClassWithNonFinalPropertyWithDefaultMapper(),
  );
  registry.registerMapper<lrptm.ClassWithNonFinalOptionalProperty>(
    lrptmrmg.ClassWithNonFinalOptionalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithLateNonFinalProperty>(
    lrptmrmg.ClassWithLateNonFinalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithLateFinalProperty>(
    lrptmrmg.ClassWithLateFinalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithMixedFinalAndLateFinalProperty>(
    lrptmrmg.ClassWithMixedFinalAndLateFinalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithMapperNamedMapperStrategy>(
    testLocalResourceMapper,
  );
  registry.registerMapper<lrptm.ClassWithMapperStrategy>(
    lrptm.TestLocalResourceMapper(),
  );
  registry.registerMapper<lrptm.ClassWithMapperInstanceStrategy>(
    const lrptm.TestLocalResourceMapper2(),
  );
  registry.registerMapper<ce.Library>(
    cermg.LibraryMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.Playlist>(
    cermg.PlaylistMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.Course>(
    cermg.CourseMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.BookCollection>(
    cermg.BookCollectionMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.Book>(cermg.BookMapper());
  registry.registerMapper<ce.Track>(cermg.TrackMapper());
  registry.registerMapper<ce.Module>(cermg.ModuleMapper());
  registry.registerMapper<ccte.Library>(
    cctermg.LibraryMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ems.Book>(
    emsrmg.BookMapper(customPriorityMapper: customPriorityMapper),
  );
  registry.registerMapper<ems.BookFormat>(emsrmg.BookFormatMapper());
  registry.registerMapper<ems.Priority>(emsrmg.PriorityMapper());
  registry.registerMapper<ems.ProductStatus>(emsrmg.ProductStatusMapper());
  registry.registerMapper<ems.ItemCondition>(emsrmg.ItemConditionMapper());
  registry.registerMapper<ems.OrderStatus>(emsrmg.OrderStatusMapper());
  registry.registerMapper<ems.CurrencyCode>(emsrmg.CurrencyCodeMapper());
  registry.registerMapper<ems.BusinessEntityType>(
    emsrmg.BusinessEntityTypeMapper(),
  );
  registry.registerMapper<ems.UserRating>(emsrmg.UserRatingMapper());
  registry.registerMapper<ems.ProductCategory>(
    emsrmg.ProductCategoryMapper(baseVocabProvider: baseVocabProvider),
  );
  registry.registerMapper<ems.ShippingMethod>(
    emsrmg.ShippingMethodMapper(
      apiBaseProvider: apiBaseProvider,
      versionProvider: versionProvider,
    ),
  );
  registry.registerMapper<ems.EmployeeRole>(
    emsrmg.EmployeeRoleMapper(
      departmentProvider: departmentProvider,
      orgNamespaceProvider: orgNamespaceProvider,
    ),
  );
  registry.registerMapper<eci.Item>(
    ecirmg.ItemMapper(storageRootProvider: storageRootProvider),
  );
  registry.registerMapper<efb.Book>(efbrmg.BookMapper());
  registry.registerMapper<efb.Chapter>(efbrmg.ChapterMapper());
  registry.registerMapper<efb.ISBN>(efbrmg.ISBNMapper());
  registry.registerMapper<efb.Rating>(efbrmg.RatingMapper());
  registry.registerMapper<efb.BookFormat>(efbrmg.BookFormatMapper());
  registry.registerMapper<eis.StandardIsbn>(eisrmg.StandardIsbnMapper());
  registry.registerMapper<eis.AbsoluteUri>(eisrmg.AbsoluteUriMapper());
  registry.registerMapper<eis.UserReference>(userReferenceMapper);
  registry.registerMapper<eis.SimpleBook>(eisrmg.SimpleBookMapper());
  registry.registerMapper<eis.Person>(eisrmg.PersonMapper());
  registry.registerMapper<eis.Chapter>(
    eisrmg.ChapterMapper(chapterIdMapper: chapterIdMapper),
  );
  registry.registerMapper<erl.EnhancedRating>(erlrmg.EnhancedRatingMapper());
  registry.registerMapper<erl.Temperature>(erlrmg.TemperatureMapper());
  registry.registerMapper<erl.LocalizedText>(erlrmg.LocalizedTextMapper());
  registry.registerMapper<inference.InferenceTestContainer>(
    irmg.InferenceTestContainerMapper(),
  );
  registry.registerMapper<lsm.Book>(lsmrmg.BookMapper());
  registry.registerMapper<provides.Parent>(
    prmg.ParentMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<nftm.SimpleBook>(
    nftmrmg.SimpleBookMapper(
      iriMapper: simpleBookIriFactory<nftm.SimpleBook>(),
    ),
  );
  registry.registerMapper<nftm.ConfigurableBook>(
    nftmrmg.ConfigurableBookMapper(
      iriMapper: configurableBookIriFactory<nftm.ConfigurableBook>(
        const nftm.IriMapperConfig(
          baseUri: 'https://books.example.com',
          format: 'detailed',
        ),
      ),
    ),
  );
  registry.registerMapper<nftm.ContextualBook>(
    nftmrmg.ContextualBookMapper(
      iriMapper: configurableBookIriFactory<nftm.ContextualBook>(
        const nftm.IriMapperConfig(
          baseUri: 'https://contextual.example.com',
          format: 'contextual',
        ),
      ),
      simpleVariant2Mapper: simpleVariantRefFactory<String>(nftm.SimpleBook),
      simpleVariantMapper: simpleVariantRefFactory<String>(nftm.SimpleBook),
    ),
  );
  registry.registerMapper<pptm.SimplePropertyTest>(
    pptmrmg.SimplePropertyTestMapper(),
  );
  registry.registerMapper<pptm.SimpleCustomPropertyTest>(
    pptmrmg.SimpleCustomPropertyTestMapper(),
  );
  registry.registerMapper<pptm.DeserializationOnlyPropertyTest>(
    pptmrmg.DeserializationOnlyPropertyTestMapper(),
  );
  registry.registerMapper<pptm.OptionalPropertyTest>(
    pptmrmg.OptionalPropertyTestMapper(),
  );
  registry.registerMapper<pptm.DefaultValueTest>(
    pptmrmg.DefaultValueTestMapper(),
  );
  registry.registerMapper<pptm.IncludeDefaultsTest>(
    pptmrmg.IncludeDefaultsTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingTest>(pptmrmg.IriMappingTestMapper());
  registry.registerMapper<pptm.IriMappingWithBaseUriTest>(
    pptmrmg.IriMappingWithBaseUriTestMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<pptm.IriMappingFullIriTest>(
    pptmrmg.IriMappingFullIriTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingFullIriSimpleTest>(
    pptmrmg.IriMappingFullIriSimpleTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingWithProviderTest>(
    pptmrmg.IriMappingWithProviderTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingWithBaseUriProviderTest>(
    pptmrmg.IriMappingWithBaseUriProviderTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingWithProviderPropertyTest>(
    pptmrmg.IriMappingWithProviderPropertyTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingWithProvidersAndBaseUriPropertyTest>(
    pptmrmg.IriMappingWithProvidersAndBaseUriPropertyTestMapper(
      baseUriProvider: baseUriProvider,
    ),
  );
  registry.registerMapper<pptm.IriMappingNamedMapperTest>(
    pptmrmg.IriMappingNamedMapperTestMapper(iriMapper: iriMapper),
  );
  registry.registerMapper<pptm.IriMappingMapperTest>(
    pptmrmg.IriMappingMapperTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingMapperInstanceTest>(
    pptmrmg.IriMappingMapperInstanceTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceMappingTest>(
    pptmrmg.LocalResourceMappingTestMapper(testLocalMapper: testLocalMapper),
  );
  registry.registerMapper<pptm.GlobalResourceMappingTest>(
    pptmrmg.GlobalResourceMappingTestMapper(testGlobalMapper: testGlobalMapper),
  );
  registry.registerMapper<pptm.LiteralMappingTest>(
    pptmrmg.LiteralMappingTestMapper(
      testLiteralPriceMapper: testLiteralPriceMapper,
    ),
  );
  registry.registerMapper<pptm.LiteralMappingTestCustomDatatype>(
    pptmrmg.LiteralMappingTestCustomDatatypeMapper(),
  );
  registry.registerMapper<pptm.CollectionNoneTest>(
    pptmrmg.CollectionNoneTestMapper(),
  );
  registry.registerMapper<pptm.CollectionAutoTest>(
    pptmrmg.CollectionAutoTestMapper(),
  );
  registry.registerMapper<pptm.CollectionTest>(pptmrmg.CollectionTestMapper());
  registry.registerMapper<pptm.CollectionIterableTest>(
    pptmrmg.CollectionIterableTestMapper(),
  );
  registry.registerMapper<pptm.MapNoCollectionNoMapperTest>(
    pptmrmg.MapNoCollectionNoMapperTestMapper(),
  );
  registry.registerMapper<pptm.MapLocalResourceMapperTest>(
    pptmrmg.MapLocalResourceMapperTestMapper(mapEntryMapper: mapEntryMapper),
  );
  registry.registerMapper<pptm.SetTest>(pptmrmg.SetTestMapper());
  registry.registerMapper<pptm.EnumTypeTest>(pptmrmg.EnumTypeTestMapper());
  registry.registerMapper<pptm.ComplexDefaultValueTest>(
    pptmrmg.ComplexDefaultValueTestMapper(),
  );
  registry.registerMapper<pptm.FinalPropertyTest>(
    pptmrmg.FinalPropertyTestMapper(),
  );
  registry.registerMapper<pptm.LatePropertyTest>(
    pptmrmg.LatePropertyTestMapper(),
  );
  registry.registerMapper<pptm.MutablePropertyTest>(
    pptmrmg.MutablePropertyTestMapper(),
  );
  registry.registerMapper<pptm.LanguageTagTest>(
    pptmrmg.LanguageTagTestMapper(),
  );
  registry.registerMapper<pptm.DatatypeTest>(pptmrmg.DatatypeTestMapper());
  registry.registerMapper<pptm.GlobalResourceNamedMapperTest>(
    pptmrmg.GlobalResourceNamedMapperTestMapper(
      testNamedMapper: testNamedMapper,
    ),
  );
  registry.registerMapper<pptm.LiteralNamedMapperTest>(
    pptmrmg.LiteralNamedMapperTestMapper(testCustomMapper: testCustomMapper),
  );
  registry.registerMapper<pptm.LiteralTypeMapperTest>(
    pptmrmg.LiteralTypeMapperTestMapper(),
  );
  registry.registerMapper<pptm.GlobalResourceTypeMapperTest>(
    pptmrmg.GlobalResourceTypeMapperTestMapper(),
  );
  registry.registerMapper<pptm.GlobalResourceMapperTest>(
    pptmrmg.GlobalResourceMapperTestMapper(),
  );
  registry.registerMapper<pptm.GlobalResourceInstanceMapperTest>(
    pptmrmg.GlobalResourceInstanceMapperTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceMapperTest>(
    pptmrmg.LocalResourceMapperTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceMapperObjectPropertyTest>(
    pptmrmg.LocalResourceMapperObjectPropertyTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceInstanceMapperTest>(
    pptmrmg.LocalResourceInstanceMapperTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceInstanceMapperObjectPropertyTest>(
    pptmrmg.LocalResourceInstanceMapperObjectPropertyTestMapper(),
  );
  registry.registerMapper<pptm.LiteralMapperTest>(
    pptmrmg.LiteralMapperTestMapper(),
  );
  registry.registerMapper<pptm.LiteralInstanceMapperTest>(
    pptmrmg.LiteralInstanceMapperTestMapper(),
  );
  registry.registerMapper<pptm.BookFormatType>(pptmrmg.BookFormatTypeMapper());
  registry.registerMapper<patm.Document>(
    patmrmg.DocumentMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<rd.RootDocument>(rdrmg.RootDocumentMapper());
  registry.registerMapper<uttm.BookWithUnmappedTriples>(
    uttmrmg.BookWithUnmappedTriplesMapper(),
  );
  registry.registerMapper<uttm.BookWithUnmappedTriplesLateFields>(
    uttmrmg.BookWithUnmappedTriplesLateFieldsMapper(),
  );
  registry.registerMapper<uttm.BookWithInvalidUnmappedTriplesType>(
    uttmrmg.BookWithInvalidUnmappedTriplesTypeMapper(),
  );
  registry.registerMapper<vgtm.NonGenericPerson>(
    vgtmrmg.NonGenericPersonMapper(),
  );
  registry.registerMapper<wftm.Document>(wftmrmg.DocumentMapper());
  registry.registerMapper<wftm.Article>(wftmrmg.ArticleMapper());
  registry.registerMapper<wftm.Page>(
    wftmrmg.PageMapper(baseUriProvider: baseUriProvider),
  );

  return rdfMapper;
}
