// GENERATED CODE - DO NOT MODIFY BY HAND
//
// This file was generated by the RDF Mapper Generator.
//
// ignore_for_file: unused_import, unnecessary_cast, prefer_const_constructors
// ignore_for_file: unnecessary_brace_in_string_interps, prefer_conditional_assignment
// ignore_for_file: lines_longer_than_80_chars, avoid_redundant_argument_values
// ignore_for_file: unused_field

import 'package:locorda_rdf_mapper/mapper.dart';

import 'fixtures/annotation_subclass_test_models.dart' as astm;
import 'fixtures/annotation_subclass_test_models.locorda_rdf_mapper.g.dart'
    as astmlrmg;
import 'fixtures/annotation_test_models.dart' as atm;
import 'fixtures/annotation_test_models.locorda_rdf_mapper.g.dart' as atmlrmg;
import 'fixtures/comprehensive_collection_tests.dart' as cct;
import 'fixtures/comprehensive_collection_tests.locorda_rdf_mapper.g.dart'
    as cctlrmg;
import 'fixtures/directional_comprehensive_test_models.dart' as dctm;
import 'fixtures/directional_comprehensive_test_models.locorda_rdf_mapper.g.dart'
    as dctmlrmg;
import 'fixtures/directional_mapper_test_models.dart' as dmtm;
import 'fixtures/directional_mapper_test_models.locorda_rdf_mapper.g.dart'
    as dmtmlrmg;
import 'fixtures/enum_test_models.dart' as etm;
import 'fixtures/enum_test_models.locorda_rdf_mapper.g.dart' as etmlrmg;
import 'fixtures/global_resource_processor_test_models.dart' as grptm;
import 'fixtures/global_resource_processor_test_models.locorda_rdf_mapper.g.dart'
    as grptmlrmg;
import 'fixtures/iri_processor_test_models.dart' as iptm;
import 'fixtures/iri_processor_test_models.locorda_rdf_mapper.g.dart'
    as iptmlrmg;
import 'fixtures/literal_processor_test_models.dart' as lptm;
import 'fixtures/literal_processor_test_models.locorda_rdf_mapper.g.dart'
    as lptmlrmg;
import 'fixtures/local_resource_processor_test_models.dart' as lrptm;
import 'fixtures/local_resource_processor_test_models.locorda_rdf_mapper.g.dart'
    as lrptmlrmg;
import 'fixtures/named_factory_test_models.dart' as nftm;
import 'fixtures/named_factory_test_models.locorda_rdf_mapper.g.dart'
    as nftmlrmg;
import 'fixtures/property_processor_test_models.dart' as pptm;
import 'fixtures/property_processor_test_models.locorda_rdf_mapper.g.dart'
    as pptmlrmg;
import 'fixtures/provided_as_test_models.dart' as patm;
import 'fixtures/provided_as_test_models.locorda_rdf_mapper.g.dart' as patmlrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/collection_examples.dart'
    as ce;
import 'fixtures/locorda_rdf_mapper_annotations/examples/collection_examples.locorda_rdf_mapper.g.dart'
    as celrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/custom_collection_type_example.dart'
    as ccte;
import 'fixtures/locorda_rdf_mapper_annotations/examples/custom_collection_type_example.locorda_rdf_mapper.g.dart'
    as cctelrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/enum_mapping_simple.dart'
    as ems;
import 'fixtures/locorda_rdf_mapper_annotations/examples/enum_mapping_simple.locorda_rdf_mapper.g.dart'
    as emslrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_crdt_item.dart' as eci;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_crdt_item.locorda_rdf_mapper.g.dart'
    as ecilrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_full_book.dart' as efb;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_full_book.locorda_rdf_mapper.g.dart'
    as efblrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_iri_strategies.dart'
    as eis;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_iri_strategies.locorda_rdf_mapper.g.dart'
    as eislrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_rdf_literal.dart'
    as erl;
import 'fixtures/locorda_rdf_mapper_annotations/examples/example_rdf_literal.locorda_rdf_mapper.g.dart'
    as erllrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/inference.dart' as inference;
import 'fixtures/locorda_rdf_mapper_annotations/examples/inference.locorda_rdf_mapper.g.dart'
    as ilrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/localized_string_map.dart'
    as lsm;
import 'fixtures/locorda_rdf_mapper_annotations/examples/localized_string_map.locorda_rdf_mapper.g.dart'
    as lsmlrmg;
import 'fixtures/locorda_rdf_mapper_annotations/examples/provides.dart' as provides;
import 'fixtures/locorda_rdf_mapper_annotations/examples/provides.locorda_rdf_mapper.g.dart'
    as plrmg;
import 'fixtures/root_document.dart' as rd;
import 'fixtures/root_document.locorda_rdf_mapper.g.dart' as rdlrmg;
import 'fixtures/unmapped_triples_test_models.dart' as uttm;
import 'fixtures/unmapped_triples_test_models.locorda_rdf_mapper.g.dart'
    as uttmlrmg;
import 'fixtures/valid_generic_test_models.dart' as vgtm;
import 'fixtures/valid_generic_test_models.locorda_rdf_mapper.g.dart'
    as vgtmlrmg;
import 'fixtures/with_fragment_test_models.dart' as wftm;
import 'fixtures/with_fragment_test_models.locorda_rdf_mapper.g.dart'
    as wftmlrmg;

/// Initializes and returns an RdfMapper with test mappers registered.
///
/// [rdfMapper] An optional RdfMapper instance to use. If not provided, a new one will be created.
/// * [$podIri$Factory]
/// * [apiBaseProvider]
/// * [baseUriProvider]
/// * [baseVocabProvider]
/// * [chapterIdMapper]
/// * [complexItemMapperGlobal]
/// * [complexItemMapperLocal]
/// * [configurableBookIriFactory]
/// * [customCollectionMapper]
/// * [customPriorityMapper]
/// * [departmentProvider]
/// * [iriMapper]
/// * [mapEntryMapper]
/// * [orgNamespaceProvider]
/// * [simpleBookIriFactory]
/// * [simpleVariantRefFactory]
/// * [storageRootProvider]
/// * [testCustomMapper]
/// * [testGlobalMapper]
/// * [testGlobalResourceMapper]
/// * [testIriMapper]
/// * [testLiteralMapper]
/// * [testLiteralPriceMapper]
/// * [testLocalMapper]
/// * [testLocalResourceMapper]
/// * [testMapper]
/// * [testMapper3]
/// * [testNamedMapper]
/// * [userReferenceMapper]
/// * [versionProvider]
RdfMapper initTestRdfMapper({
  RdfMapper? rdfMapper,
  required IriTermMapper<(String id,)> Function<T>(astm.PodConfig)
  $podIri$Factory,
  required String Function() apiBaseProvider,
  required String Function() baseUriProvider,
  required String Function() baseVocabProvider,
  required IriTermMapper<(String bookId, int chapterNumber)> chapterIdMapper,
  required GlobalResourceMapper<cct.ComplexItem> complexItemMapperGlobal,
  required LocalResourceMapper<cct.ComplexItem> complexItemMapperLocal,
  required IriTermMapper<(String id,)> Function<T>(nftm.IriMapperConfig)
  configurableBookIriFactory,
  required Mapper<List<String>> customCollectionMapper,
  required LiteralTermMapper<ems.Priority> customPriorityMapper,
  required String Function() departmentProvider,
  required IriTermMapper<String> iriMapper,
  required LocalResourceMapper<MapEntry<String, String>> mapEntryMapper,
  required String Function() orgNamespaceProvider,
  required IriTermMapper<(String id,)> Function<T>() simpleBookIriFactory,
  required IriTermMapper<String> Function<T>(Type) simpleVariantRefFactory,
  required String Function() storageRootProvider,
  required LiteralTermMapper<String> testCustomMapper,
  required GlobalResourceMapper<Object> testGlobalMapper,
  required GlobalResourceMapper<grptm.ClassWithMapperNamedMapperStrategy>
  testGlobalResourceMapper,
  required IriTermMapper<iptm.IriWithNamedMapper> testIriMapper,
  required LiteralTermMapper<lptm.LiteralWithNamedMapper> testLiteralMapper,
  required LiteralTermMapper<double> testLiteralPriceMapper,
  required LocalResourceMapper<Object> testLocalMapper,
  required LocalResourceMapper<lrptm.ClassWithMapperNamedMapperStrategy>
  testLocalResourceMapper,
  required IriTermMapper<grptm.ClassWithIriNamedMapperStrategy> testMapper,
  required IriTermMapper<(String id, String surname, int version)> testMapper3,
  required GlobalResourceMapper<Object> testNamedMapper,
  required IriTermMapper<eis.UserReference> userReferenceMapper,
  required String Function() versionProvider,
}) {
  if (rdfMapper == null) {
    rdfMapper = RdfMapper.withDefaultRegistry();
  }
  var registry = rdfMapper.registry;

  registry.registerMapper<astm.BookWithCustomAnnotation>(
    astmlrmg.BookWithCustomAnnotationMapper(),
  );
  registry.registerMapper<astm.PersonWithPodResource>(
    astmlrmg.PersonWithPodResourceMapper(),
  );
  registry.registerMapper<astm.PersonWithPodResource2>(
    astmlrmg.PersonWithPodResource2Mapper(
      iriMapper: $podIri$Factory<astm.PersonWithPodResource2>(
        const astm.PodConfig(digits: 2),
      ),
    ),
  );
  registry.registerMapper<astm.ArticleWithRegularAnnotation>(
    astmlrmg.ArticleWithRegularAnnotationMapper(),
  );
  registry.registerMapper<atm.BookWithMapper>(atmlrmg.BookWithMapperMapper());
  registry.registerMapper<atm.BookWithTemplate>(
    atmlrmg.BookWithTemplateMapper(),
  );
  registry.registerMapper<cct.RegistryCollectionTests>(
    cctlrmg.RegistryCollectionTestsMapper(),
  );
  registry.registerMapper<cct.NamedMapperCollectionTests>(
    cctlrmg.NamedMapperCollectionTestsMapper(
      customCollectionMapper: customCollectionMapper,
    ),
  );
  registry.registerMapper<cct.SelfContainedMapperTests>(
    cctlrmg.SelfContainedMapperTestsMapper(),
  );
  registry.registerMapper<cct.InstanceManagedCollectionTests>(
    cctlrmg.InstanceManagedCollectionTestsMapper(),
  );
  registry.registerMapper<cct.SetAndIterableCollectionTests>(
    cctlrmg.SetAndIterableCollectionTestsMapper(),
  );
  registry.registerMapper<cct.ComplexItem>(cctlrmg.ComplexItemMapper());
  registry.registerMapper<cct.ItemTypeParameterTests>(
    cctlrmg.ItemTypeParameterTestsMapper(
      complexItemMapperLocal: complexItemMapperLocal,
    ),
  );
  registry.registerMapper<cct.CombinedItemMappingTests>(
    cctlrmg.CombinedItemMappingTestsMapper(
      baseUriProvider: baseUriProvider,
      complexItemMapperGlobal: complexItemMapperGlobal,
    ),
  );
  registry.registerMapper<cct.EdgeCaseTests>(cctlrmg.EdgeCaseTestsMapper());
  registry.registerMapper<cct.PerformanceTests>(
    cctlrmg.PerformanceTestsMapper(),
  );
  registry.registerMapper<cct.MapCollectionTests>(
    cctlrmg.MapCollectionTestsMapper(),
  );
  registry.registerMapper<cct.DefaultSerializationTests>(
    cctlrmg.DefaultSerializationTestsMapper(),
  );
  registry.registerMapper<cct.NestedCollectionTests>(
    cctlrmg.NestedCollectionTestsMapper(),
  );
  registry.registerMapper<cct.MixedTypeTests>(cctlrmg.MixedTypeTestsMapper());
  registry.registerMapper<cct.ContextProviderTests>(
    cctlrmg.ContextProviderTestsMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyGlobalResource>(
    dctmlrmg.DeserializeOnlyGlobalResourceMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyGlobalResource>(
    dctmlrmg.SerializeOnlyGlobalResourceMapper(),
  );
  registry.registerMapper<dctm.BidirectionalGlobalResource>(
    dctmlrmg.BidirectionalGlobalResourceMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyLocalResource>(
    dctmlrmg.DeserializeOnlyLocalResourceMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyLocalResource>(
    dctmlrmg.SerializeOnlyLocalResourceMapper(),
  );
  registry.registerMapper<dctm.BidirectionalLocalResource>(
    dctmlrmg.BidirectionalLocalResourceMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyIriClass>(
    dctmlrmg.DeserializeOnlyIriClassMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyIriClass>(
    dctmlrmg.SerializeOnlyIriClassMapper(),
  );
  registry.registerMapper<dctm.BidirectionalIriClass>(
    dctmlrmg.BidirectionalIriClassMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyLiteralClass>(
    dctmlrmg.DeserializeOnlyLiteralClassMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyLiteralClass>(
    dctmlrmg.SerializeOnlyLiteralClassMapper(),
  );
  registry.registerMapper<dctm.BidirectionalLiteralClass>(
    dctmlrmg.BidirectionalLiteralClassMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyIriEnum>(
    dctmlrmg.DeserializeOnlyIriEnumMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyIriEnum>(
    dctmlrmg.SerializeOnlyIriEnumMapper(),
  );
  registry.registerMapper<dctm.BidirectionalIriEnum>(
    dctmlrmg.BidirectionalIriEnumMapper(),
  );
  registry.registerDeserializer<dctm.DeserializeOnlyLiteralEnum>(
    dctmlrmg.DeserializeOnlyLiteralEnumMapper(),
  );
  registry.registerSerializer<dctm.SerializeOnlyLiteralEnum>(
    dctmlrmg.SerializeOnlyLiteralEnumMapper(),
  );
  registry.registerMapper<dctm.BidirectionalLiteralEnum>(
    dctmlrmg.BidirectionalLiteralEnumMapper(),
  );
  registry.registerDeserializer<dmtm.DeserializeOnlyClass>(
    dmtmlrmg.DeserializeOnlyClassMapper(),
  );
  registry.registerSerializer<dmtm.SerializeOnlyClass>(
    dmtmlrmg.SerializeOnlyClassMapper(),
  );
  registry.registerMapper<dmtm.BidirectionalClass>(
    dmtmlrmg.BidirectionalClassMapper(),
  );
  registry.registerMapper<etm.Priority>(etmlrmg.PriorityMapper());
  registry.registerMapper<etm.Status>(etmlrmg.StatusMapper());
  registry.registerMapper<etm.DocumentType>(etmlrmg.DocumentTypeMapper());
  registry.registerMapper<etm.CategoryType>(etmlrmg.CategoryTypeMapper());
  registry.registerMapper<etm.FileFormat>(
    etmlrmg.FileFormatMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<grptm.Book>(grptmlrmg.BookMapper());
  registry.registerMapper<grptm.ClassWithEmptyIriStrategy>(
    grptmlrmg.ClassWithEmptyIriStrategyMapper(),
  );
  registry.registerMapper<grptm.ClassWithNoRdfType>(
    grptmlrmg.ClassWithNoRdfTypeMapper(),
  );
  registry.registerMapper<grptm.ClassWithIriTemplateStrategy>(
    grptmlrmg.ClassWithIriTemplateStrategyMapper(),
  );
  registry.registerMapper<grptm.ClassWithIriTemplateAndContextVariableStrategy>(
    grptmlrmg.ClassWithIriTemplateAndContextVariableStrategyMapper(
      baseUriProvider: baseUriProvider,
    ),
  );
  registry.registerMapper<grptm.ClassWithIriNamedMapperStrategy>(
    grptmlrmg.ClassWithIriNamedMapperStrategyMapper(testMapper: testMapper),
  );
  registry.registerMapper<
    grptm.ClassWithIriNamedMapperStrategy2PartsWithProperties
  >(
    grptmlrmg.ClassWithIriNamedMapperStrategy2PartsWithPropertiesMapper(
      testMapper3: testMapper3,
    ),
  );
  registry.registerMapper<grptm.ClassWithIriMapperStrategy>(
    grptmlrmg.ClassWithIriMapperStrategyMapper(),
  );
  registry.registerMapper<grptm.ClassWithIriMapperInstanceStrategy>(
    grptmlrmg.ClassWithIriMapperInstanceStrategyMapper(),
  );
  registry.registerMapper<grptm.ClassWithMapperNamedMapperStrategy>(
    testGlobalResourceMapper,
  );
  registry.registerMapper<grptm.ClassWithMapperStrategy>(
    grptm.TestGlobalResourceMapper(),
  );
  registry.registerMapper<grptm.ClassWithMapperInstanceStrategy>(
    const grptm.TestGlobalResourceMapper2(),
  );
  registry.registerMapper<iptm.IriWithOnePart>(iptmlrmg.IriWithOnePartMapper());
  registry.registerMapper<iptm.IriWithOnePartExplicitlyGlobal>(
    iptmlrmg.IriWithOnePartExplicitlyGlobalMapper(),
  );
  registry.registerMapper<iptm.IriWithOnePartNamed>(
    iptmlrmg.IriWithOnePartNamedMapper(),
  );
  registry.registerMapper<iptm.IriWithTwoParts>(
    iptmlrmg.IriWithTwoPartsMapper(),
  );
  registry.registerMapper<iptm.IriWithBaseUriAndTwoParts>(
    iptmlrmg.IriWithBaseUriAndTwoPartsMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<iptm.IriWithBaseUri>(
    iptmlrmg.IriWithBaseUriMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<iptm.IriWithNamedMapper>(testIriMapper);
  registry.registerMapper<iptm.IriWithMapper>(iptm.TestIriMapper());
  registry.registerMapper<iptm.IriWithMapperInstance>(
    const iptm.TestIriMapper2(),
  );
  registry.registerMapper<iptm.IriWithNonConstructorFields>(
    iptmlrmg.IriWithNonConstructorFieldsMapper(),
  );
  registry.registerMapper<iptm.IriWithMixedFields>(
    iptmlrmg.IriWithMixedFieldsMapper(),
  );
  registry.registerMapper<lptm.LiteralString>(lptmlrmg.LiteralStringMapper());
  registry.registerMapper<lptm.Rating>(lptmlrmg.RatingMapper());
  registry.registerMapper<lptm.LocalizedText>(lptmlrmg.LocalizedTextMapper());
  registry.registerMapper<lptm.LiteralDouble>(lptmlrmg.LiteralDoubleMapper());
  registry.registerMapper<lptm.LiteralInteger>(lptmlrmg.LiteralIntegerMapper());
  registry.registerMapper<lptm.Temperature>(lptmlrmg.TemperatureMapper());
  registry.registerMapper<lptm.CustomLocalizedText>(
    lptmlrmg.CustomLocalizedTextMapper(),
  );
  registry.registerMapper<lptm.DoubleAsMilliunit>(
    lptmlrmg.DoubleAsMilliunitMapper(),
  );
  registry.registerMapper<lptm.LiteralWithNamedMapper>(testLiteralMapper);
  registry.registerMapper<lptm.LiteralWithMapper>(lptm.TestLiteralMapper());
  registry.registerMapper<lptm.LiteralWithMapperInstance>(
    const lptm.TestLiteralMapper2(),
  );
  registry.registerMapper<lptm.LiteralWithNonConstructorValue>(
    lptmlrmg.LiteralWithNonConstructorValueMapper(),
  );
  registry.registerMapper<lptm.LocalizedTextWithNonConstructorLanguage>(
    lptmlrmg.LocalizedTextWithNonConstructorLanguageMapper(),
  );
  registry.registerMapper<lptm.LiteralLateFinalLocalizedText>(
    lptmlrmg.LiteralLateFinalLocalizedTextMapper(),
  );
  registry.registerMapper<lrptm.Book>(lrptmlrmg.BookMapper());
  registry.registerMapper<lrptm.ClassWithNoRdfType>(
    lrptmlrmg.ClassWithNoRdfTypeMapper(),
  );
  registry.registerMapper<lrptm.ClassWithPositionalProperty>(
    lrptmlrmg.ClassWithPositionalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithNonFinalProperty>(
    lrptmlrmg.ClassWithNonFinalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithNonFinalPropertyWithDefault>(
    lrptmlrmg.ClassWithNonFinalPropertyWithDefaultMapper(),
  );
  registry.registerMapper<lrptm.ClassWithNonFinalOptionalProperty>(
    lrptmlrmg.ClassWithNonFinalOptionalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithLateNonFinalProperty>(
    lrptmlrmg.ClassWithLateNonFinalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithLateFinalProperty>(
    lrptmlrmg.ClassWithLateFinalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithMixedFinalAndLateFinalProperty>(
    lrptmlrmg.ClassWithMixedFinalAndLateFinalPropertyMapper(),
  );
  registry.registerMapper<lrptm.ClassWithMapperNamedMapperStrategy>(
    testLocalResourceMapper,
  );
  registry.registerMapper<lrptm.ClassWithMapperStrategy>(
    lrptm.TestLocalResourceMapper(),
  );
  registry.registerMapper<lrptm.ClassWithMapperInstanceStrategy>(
    const lrptm.TestLocalResourceMapper2(),
  );
  registry.registerMapper<nftm.SimpleBook>(
    nftmlrmg.SimpleBookMapper(
      iriMapper: simpleBookIriFactory<nftm.SimpleBook>(),
    ),
  );
  registry.registerMapper<nftm.ConfigurableBook>(
    nftmlrmg.ConfigurableBookMapper(
      iriMapper: configurableBookIriFactory<nftm.ConfigurableBook>(
        const nftm.IriMapperConfig(
          baseUri: 'https://books.example.com',
          format: 'detailed',
        ),
      ),
    ),
  );
  registry.registerMapper<nftm.ContextualBook>(
    nftmlrmg.ContextualBookMapper(
      iriMapper: configurableBookIriFactory<nftm.ContextualBook>(
        const nftm.IriMapperConfig(
          baseUri: 'https://contextual.example.com',
          format: 'contextual',
        ),
      ),
      simpleVariant2Mapper: simpleVariantRefFactory<String>(nftm.SimpleBook),
      simpleVariantMapper: simpleVariantRefFactory<String>(nftm.SimpleBook),
    ),
  );
  registry.registerMapper<pptm.SimplePropertyTest>(
    pptmlrmg.SimplePropertyTestMapper(),
  );
  registry.registerMapper<pptm.SimpleCustomPropertyTest>(
    pptmlrmg.SimpleCustomPropertyTestMapper(),
  );
  registry.registerMapper<pptm.DeserializationOnlyPropertyTest>(
    pptmlrmg.DeserializationOnlyPropertyTestMapper(),
  );
  registry.registerMapper<pptm.OptionalPropertyTest>(
    pptmlrmg.OptionalPropertyTestMapper(),
  );
  registry.registerMapper<pptm.DefaultValueTest>(
    pptmlrmg.DefaultValueTestMapper(),
  );
  registry.registerMapper<pptm.IncludeDefaultsTest>(
    pptmlrmg.IncludeDefaultsTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingTest>(pptmlrmg.IriMappingTestMapper());
  registry.registerMapper<pptm.IriMappingWithBaseUriTest>(
    pptmlrmg.IriMappingWithBaseUriTestMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<pptm.IriMappingFullIriTest>(
    pptmlrmg.IriMappingFullIriTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingFullIriSimpleTest>(
    pptmlrmg.IriMappingFullIriSimpleTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingWithProviderTest>(
    pptmlrmg.IriMappingWithProviderTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingWithBaseUriProviderTest>(
    pptmlrmg.IriMappingWithBaseUriProviderTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingWithProviderPropertyTest>(
    pptmlrmg.IriMappingWithProviderPropertyTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingWithProvidersAndBaseUriPropertyTest>(
    pptmlrmg.IriMappingWithProvidersAndBaseUriPropertyTestMapper(
      baseUriProvider: baseUriProvider,
    ),
  );
  registry.registerMapper<pptm.IriMappingNamedMapperTest>(
    pptmlrmg.IriMappingNamedMapperTestMapper(iriMapper: iriMapper),
  );
  registry.registerMapper<pptm.IriMappingMapperTest>(
    pptmlrmg.IriMappingMapperTestMapper(),
  );
  registry.registerMapper<pptm.IriMappingMapperInstanceTest>(
    pptmlrmg.IriMappingMapperInstanceTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceMappingTest>(
    pptmlrmg.LocalResourceMappingTestMapper(testLocalMapper: testLocalMapper),
  );
  registry.registerMapper<pptm.GlobalResourceMappingTest>(
    pptmlrmg.GlobalResourceMappingTestMapper(
      testGlobalMapper: testGlobalMapper,
    ),
  );
  registry.registerMapper<pptm.LiteralMappingTest>(
    pptmlrmg.LiteralMappingTestMapper(
      testLiteralPriceMapper: testLiteralPriceMapper,
    ),
  );
  registry.registerMapper<pptm.LiteralMappingTestCustomDatatype>(
    pptmlrmg.LiteralMappingTestCustomDatatypeMapper(),
  );
  registry.registerMapper<pptm.CollectionNoneTest>(
    pptmlrmg.CollectionNoneTestMapper(),
  );
  registry.registerMapper<pptm.CollectionAutoTest>(
    pptmlrmg.CollectionAutoTestMapper(),
  );
  registry.registerMapper<pptm.CollectionTest>(pptmlrmg.CollectionTestMapper());
  registry.registerMapper<pptm.CollectionIterableTest>(
    pptmlrmg.CollectionIterableTestMapper(),
  );
  registry.registerMapper<pptm.MapNoCollectionNoMapperTest>(
    pptmlrmg.MapNoCollectionNoMapperTestMapper(),
  );
  registry.registerMapper<pptm.MapLocalResourceMapperTest>(
    pptmlrmg.MapLocalResourceMapperTestMapper(mapEntryMapper: mapEntryMapper),
  );
  registry.registerMapper<pptm.SetTest>(pptmlrmg.SetTestMapper());
  registry.registerMapper<pptm.EnumTypeTest>(pptmlrmg.EnumTypeTestMapper());
  registry.registerMapper<pptm.ComplexDefaultValueTest>(
    pptmlrmg.ComplexDefaultValueTestMapper(),
  );
  registry.registerMapper<pptm.FinalPropertyTest>(
    pptmlrmg.FinalPropertyTestMapper(),
  );
  registry.registerMapper<pptm.LatePropertyTest>(
    pptmlrmg.LatePropertyTestMapper(),
  );
  registry.registerMapper<pptm.MutablePropertyTest>(
    pptmlrmg.MutablePropertyTestMapper(),
  );
  registry.registerMapper<pptm.LanguageTagTest>(
    pptmlrmg.LanguageTagTestMapper(),
  );
  registry.registerMapper<pptm.DatatypeTest>(pptmlrmg.DatatypeTestMapper());
  registry.registerMapper<pptm.GlobalResourceNamedMapperTest>(
    pptmlrmg.GlobalResourceNamedMapperTestMapper(
      testNamedMapper: testNamedMapper,
    ),
  );
  registry.registerMapper<pptm.LiteralNamedMapperTest>(
    pptmlrmg.LiteralNamedMapperTestMapper(testCustomMapper: testCustomMapper),
  );
  registry.registerMapper<pptm.LiteralTypeMapperTest>(
    pptmlrmg.LiteralTypeMapperTestMapper(),
  );
  registry.registerMapper<pptm.GlobalResourceTypeMapperTest>(
    pptmlrmg.GlobalResourceTypeMapperTestMapper(),
  );
  registry.registerMapper<pptm.GlobalResourceMapperTest>(
    pptmlrmg.GlobalResourceMapperTestMapper(),
  );
  registry.registerMapper<pptm.GlobalResourceInstanceMapperTest>(
    pptmlrmg.GlobalResourceInstanceMapperTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceMapperTest>(
    pptmlrmg.LocalResourceMapperTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceMapperObjectPropertyTest>(
    pptmlrmg.LocalResourceMapperObjectPropertyTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceInstanceMapperTest>(
    pptmlrmg.LocalResourceInstanceMapperTestMapper(),
  );
  registry.registerMapper<pptm.LocalResourceInstanceMapperObjectPropertyTest>(
    pptmlrmg.LocalResourceInstanceMapperObjectPropertyTestMapper(),
  );
  registry.registerMapper<pptm.LiteralMapperTest>(
    pptmlrmg.LiteralMapperTestMapper(),
  );
  registry.registerMapper<pptm.LiteralInstanceMapperTest>(
    pptmlrmg.LiteralInstanceMapperTestMapper(),
  );
  registry.registerMapper<pptm.BookFormatType>(pptmlrmg.BookFormatTypeMapper());
  registry.registerMapper<patm.Document>(
    patmlrmg.DocumentMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.Library>(
    celrmg.LibraryMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.Playlist>(
    celrmg.PlaylistMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.Course>(
    celrmg.CourseMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.BookCollection>(
    celrmg.BookCollectionMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ce.Book>(celrmg.BookMapper());
  registry.registerMapper<ce.Track>(celrmg.TrackMapper());
  registry.registerMapper<ce.Module>(celrmg.ModuleMapper());
  registry.registerMapper<ccte.Library>(
    cctelrmg.LibraryMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<ems.Book>(
    emslrmg.BookMapper(customPriorityMapper: customPriorityMapper),
  );
  registry.registerMapper<ems.BookFormat>(emslrmg.BookFormatMapper());
  registry.registerMapper<ems.Priority>(emslrmg.PriorityMapper());
  registry.registerMapper<ems.ProductStatus>(emslrmg.ProductStatusMapper());
  registry.registerMapper<ems.ItemCondition>(emslrmg.ItemConditionMapper());
  registry.registerMapper<ems.OrderStatus>(emslrmg.OrderStatusMapper());
  registry.registerMapper<ems.CurrencyCode>(emslrmg.CurrencyCodeMapper());
  registry.registerMapper<ems.BusinessEntityType>(
    emslrmg.BusinessEntityTypeMapper(),
  );
  registry.registerMapper<ems.UserRating>(emslrmg.UserRatingMapper());
  registry.registerMapper<ems.ProductCategory>(
    emslrmg.ProductCategoryMapper(baseVocabProvider: baseVocabProvider),
  );
  registry.registerMapper<ems.ShippingMethod>(
    emslrmg.ShippingMethodMapper(
      apiBaseProvider: apiBaseProvider,
      versionProvider: versionProvider,
    ),
  );
  registry.registerMapper<ems.EmployeeRole>(
    emslrmg.EmployeeRoleMapper(
      departmentProvider: departmentProvider,
      orgNamespaceProvider: orgNamespaceProvider,
    ),
  );
  registry.registerMapper<eci.Item>(
    ecilrmg.ItemMapper(storageRootProvider: storageRootProvider),
  );
  registry.registerMapper<efb.Book>(efblrmg.BookMapper());
  registry.registerMapper<efb.Chapter>(efblrmg.ChapterMapper());
  registry.registerMapper<efb.ISBN>(efblrmg.ISBNMapper());
  registry.registerMapper<efb.Rating>(efblrmg.RatingMapper());
  registry.registerMapper<efb.BookFormat>(efblrmg.BookFormatMapper());
  registry.registerMapper<eis.StandardIsbn>(eislrmg.StandardIsbnMapper());
  registry.registerMapper<eis.AbsoluteUri>(eislrmg.AbsoluteUriMapper());
  registry.registerMapper<eis.UserReference>(userReferenceMapper);
  registry.registerMapper<eis.SimpleBook>(eislrmg.SimpleBookMapper());
  registry.registerMapper<eis.Person>(eislrmg.PersonMapper());
  registry.registerMapper<eis.Chapter>(
    eislrmg.ChapterMapper(chapterIdMapper: chapterIdMapper),
  );
  registry.registerMapper<erl.EnhancedRating>(erllrmg.EnhancedRatingMapper());
  registry.registerMapper<erl.Temperature>(erllrmg.TemperatureMapper());
  registry.registerMapper<erl.LocalizedText>(erllrmg.LocalizedTextMapper());
  registry.registerMapper<inference.InferenceTestContainer>(
    ilrmg.InferenceTestContainerMapper(),
  );
  registry.registerMapper<lsm.Book>(lsmlrmg.BookMapper());
  registry.registerMapper<provides.Parent>(
    plrmg.ParentMapper(baseUriProvider: baseUriProvider),
  );
  registry.registerMapper<rd.RootDocument>(rdlrmg.RootDocumentMapper());
  registry.registerMapper<uttm.BookWithUnmappedTriples>(
    uttmlrmg.BookWithUnmappedTriplesMapper(),
  );
  registry.registerMapper<uttm.BookWithUnmappedTriplesLateFields>(
    uttmlrmg.BookWithUnmappedTriplesLateFieldsMapper(),
  );
  registry.registerMapper<uttm.BookWithInvalidUnmappedTriplesType>(
    uttmlrmg.BookWithInvalidUnmappedTriplesTypeMapper(),
  );
  registry.registerMapper<vgtm.NonGenericPerson>(
    vgtmlrmg.NonGenericPersonMapper(),
  );
  registry.registerMapper<wftm.Document>(wftmlrmg.DocumentMapper());
  registry.registerMapper<wftm.Article>(wftmlrmg.ArticleMapper());
  registry.registerMapper<wftm.Page>(
    wftmlrmg.PageMapper(baseUriProvider: baseUriProvider),
  );

  return rdfMapper;
}
