# RDF Vocabulary to Dart Configuration
# This file configures the build_runner for generating Dart classes from RDF vocabularies.

targets:
  $default:
    builders:
      # Builder identifier in the format <package_name>|<builder_name>
      # Used to reference this builder in dependencies
      locorda_rdf_terms_generator|rdf_terms_generator:
        enabled: true
        options:
          # List of paths to JSON files containing vocabulary configurations
          # Files are merged in order, with later files overriding earlier ones at field level
          # Standard vocabularies are always loaded automatically as the base layer
          # Supports package: URLs (e.g., "package:other_package/vocabularies.json")
          # Default (if not specified): ["lib/src/vocabularies.json"]
          vocabulary_configs:
            - "lib/src/vocab/vocabularies.json"
          # Directory where generated Dart files will be output
          output_dir: "lib/src/vocab/generated"
          # Optional: Directory for caching downloaded vocabularies (default: not set)
          # When set, vocabularies are cached locally and reused instead of re-downloading
          # Cached files use the pattern: {name}.{extension} (e.g., schema.ttl, foaf.rdf)
          # cache_dir: ".dart_tool/rdf_vocabulary_cache"
  test_vocab:
    sources:
      include:
        - "test/assets/*.vocab.json"
    builders:
      locorda_rdf_terms_generator|rdf_terms_generator:
        enabled: true
        options:
          vocabulary_configs:
            - "test/assets/test_manifest.vocab.json"
          output_dir: "test/src/generated"
      mockito|mockBuilder:
        enabled: false

builders:
  # Builder name, referenced in the targets section above
  rdf_terms_generator:
    # Entry point for the builder implementation
    import: "package:locorda_rdf_terms_generator/builder.dart"
    # Factory function that creates the builder instance
    builder_factories: ["rdfVocabularyToDart"]
    # Mapping of input file extensions to output file patterns
    # The actual output paths are determined by the Builder's buildExtensions getter based on output_dir config
    build_extensions: {
      ".json": ["**/*.dart"],
    }
    # Specifies that output goes to the source tree (not to .dart_tool)
    build_to: source
    # Automatically applies this builder to packages that depend on locorda_rdf_terms_generator
    auto_apply: dependents