name: locorda_rdf_benchmark
description: Performance benchmarks for all RDF codecs in the locorda_rdf suite.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  locorda_rdf_canonicalization: ^0.12.2
  locorda_rdf_core: ^0.12.2
  locorda_rdf_jelly: ^0.12.2
  locorda_rdf_xml: ^0.12.2
  locorda_rdf_jsonld: ^0.12.2
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
