name: locorda_rdf_xml
description: >-
  A Dart RDF/XML parser and serializer. W3C-compliant decoder and encoder for
  RDF graphs in XML format.
version: 0.12.2
resolution: workspace
homepage: https://locorda.dev/rdf/xml
repository: https://github.com/locorda/rdf
issue_tracker: https://github.com/locorda/rdf/issues
documentation: https://locorda.dev/rdf/xml
topics:
  - rdf
  - linked-data
  - semantic-web
  - xml
  - knowledge-graph
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kalaß <habbatical@gmail.com>"
environment:
  sdk: ^3.7.0
dependencies:
  logging: ^1.2.0
  xml: ^6.3.0
  locorda_rdf_core: ^0.12.2
dev_dependencies:
  test: ^1.25.0
  yaml: ^3.1.2
  path: ^1.8.0
  locorda_rdf_canonicalization: ^0.12.2
  lints: ^6.0.0


  
